// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Sample.Site.Account {
	
	
	public partial class ChangePasswordSuccess {
		
		protected System.Web.UI.WebControls.Content HeaderContent;
		
		protected System.Web.UI.WebControls.Content BodyContent;
	}
}
